### ISSUE TITLE
Not Worked

### ISSUE THREAD

**Issue by Nayeb-karimi** [Jonarod/nativescript-vue-stripe-demo#1]
It's not showing anything!!!!!

**Comment by AngeloAnolin** [comment]
Is it likely you forgot to add the following in your main.js file the following snippet:

`Vue.registerElement('CreditCardView', () => require('nativescript-stripe').CreditCardView)`

**Comment by Jonarod** [comment]
@Nayeb-karimi of course, it is a repo to show the bug... Will destroy out right now, makes no sense to keep that...
