### ISSUE TITLE
Complete Working Demo

### ISSUE THREAD

**Issue by AngeloAnolin** [Jonarod/nativescript-vue-stripe-demo#2]
Not sure if you are still maintaining this, but it would be helpful if the whole process flow is completed.

Right now, this demo only displays an input field where you could enter your card information, expiry date and CVV numbers.

There should be a next step, where for example, integration with Stripe happens so that a payment charge is made, and the required tokens are provided back (payment verification, id, etc.)

Thanks.

**Comment by Jonarod** [comment]
This repo is to be destroyed... It was a repo to show a bug to the original NS-Vue-Stripe author...
